[versions]
android-gradle = "8.9.0"
compose = "1.7.3"
jfa = "715dbc9dc5"
jna = "5.17.0"
jsystemthemedetector = "7dde337429"
kotlin = "2.1.10"
mavenPublish = "0.31.0"

[libraries]
jfa = { module = "com.github.zacharee:jfa", version.ref = "jfa" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
jsystemthemedetector = { module = "com.github.zacharee:jSystemThemeDetector", version.ref = "jsystemthemedetector" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
